### ISSUE TITLE
Needs updating: latest version is 3.1.1

### ISSUE THREAD

**Issue by jabellcu** [conda-forge/visidata-feedstock#34]
### Comment:

The current version of visidata available in conda-forge is 2.1.1. this version is problematic in Windows (see https://github.com/saulpw/visidata/issues/725). The latest available version in the pip is 3.1.1, which resolves the issue. Is it possible to update it? Many thanks.

**Comment by mikev-junimo** [comment]
@anjakefala, any chance you could help out on this one? very much appreciated!

**Comment by anjakefala** [comment]
Hi! I bumped it to v3.1.1. Thanks for the ping. =)

Please try it out, and let me know everything is working.
